### ISSUE TITLE
Empty string should return whole collection

### ISSUE THREAD

**Issue by guillaumebriday** [vuex-orm/plugin-search#11]
Hey, 

I updated from 0.23 to 0.24 and empty search param now returns nothing with an error:
`Error in render: "TypeError: t is null"`

I need to start typing something to see results.

It's maybe a regression, I could open a PR if needed unless with know how to fix it quickly.

Thanks in advance

**Comment by diegopamio** [comment]
I'm having the same issue

**Comment by guillaumebriday** [comment]
a PR is opened if you want to use it directly or to review it 👍

**Comment by diegopamio** [comment]
Yes, thank you for that! But I'm concerned that it is from an early version of the library, right? I'm not sure it will work with the latest vuex-orm.

**Comment by diegopamio** [comment]
Thanks!!!

**Comment by cuebit** [comment]
I'm refactoring the plugin to align it with the most recent version of Fuse.js

The latest version of Fuse.js introduces breaking changes and as such the search plugin will endure the same fate.

You can follow the progress over in the [dev](https://github.com/vuex-orm/plugin-search/tree/dev) branch.

**Comment by guillaumebriday** [comment]
Great! Thanks 👍
