### ISSUE TITLE
Support for Vuex ORM Next

### ISSUE THREAD

**Issue by ghost** [vuex-orm/plugin-search#18]
Hi guys,

I was wondering if there are any plans to rewrite this plugin to support the Next branch of Vuex ORM in the near future? 

I have written a quick implementation for using fuse.js with Vuex ORM Next and am wondering if I should publish it. If you have plans to support the upcoming version though it would probably not make much sense to publish a package with basically the same functionality.

**Comment by cuebit** [comment]
Good question!

My understanding is that all official plugins will be accompanying the release of Vuex ORM 1.0 (next branch). 

There's still a fair bit of ground to be covered before the next iteration provides a good foundation for the ecosystem to consider its workload. That said, many of the plugins are also undergoing scrutiny to establish what sort of features are going to be offered going forward. Alas, once the next branch is in a good place, we'll be able to provide more insight. 

In the meantime, I don't see any reason preventing you from publishing something to suite your own needs. Perhaps your ideology with your plugin may prove insightful for the official plugin 👍
