### ISSUE TITLE
Composite primary key support

### ISSUE THREAD

**Issue by kiaking** [vuex-orm/plugin-search#2]
Vuex ORM 0.16.0 introduced the composite primary key feature. So now `this.entity.primaryKey` could be a `string` or an `array`.

I think we should fix [this line](https://github.com/vuex-orm/plugin-search/blob/master/src/index.js#L47) but not sure how composite key should work with the plugin.

Maybe it's better not to remove primary keys if it's composite? Since primary key could be `['post_id', 'username']`.

**Comment by cjcrawford** [comment]
Fixed in 0.23.2
