### ISSUE TITLE
Able to search many-to-many fields?

### ISSUE THREAD

**Issue by pcate-coreonyx** [vuex-orm/plugin-search#3]
I have a model with several many-to-many relationship fields, which require an intermediate pivot model. 

It doesn't appear that the search is working for them. Is this a limitation or is there a way to include these as well.

**Comment by pcate-coreonyx** [comment]
According to the [Fuse.js documentation](http://fusejs.io/#searching-in-arrays-of-objects) this should be possible, but I still have not been able to get it to work. Any help is appreciated.

**Comment by kiaking** [comment]
Hi! Sorry for being super slow on this one. We need to update the code entirely here. We're working on it, and will be coming back to this issue as soon as possible!

**Comment by kiaking** [comment]
Sorry for being so late! now with the new version, the plugin should work with the latest Vuex ORM. For your question, to search inside relationship, you should use relationship constraints.

```js
User.query().with('roles', (query) => {
  query.search('admin')
}).get()
```

I'll be closing the issue since it's very old, but please let me know if you have anything!
