### ISSUE TITLE
weird behaviour when trying to search inside fields that contain special characters

### ISSUE THREAD

**Issue by vesper8** [vuex-orm/plugin-search#4]
I have a field that contains values such as "$12 per hour" and "55% equity"

No matter what I've tried, I cannot match those fields when searching for words like "hour" or "equity", and if I search for "55" it does match the "55% equity" but if I search for "12" it does not match the "$12 per hour"

I tried many options but it still won't work

**Comment by vesper8** [comment]
ah nevermind.. I guess it was a problem with the threshold.. it seems that with the default threshold of 0 it only tries to do perfect matches.. which translates into "if it doesn't match the first word in a long string, then it returns no match"

this default seems way too strict for most use cases

**Comment by kiaking** [comment]
Ah, good point. Yeah I think we should change it to have bigger treshhold.
