### ISSUE TITLE
Typescript error with new version of vuex-orm

### ISSUE THREAD

**Issue by abdullahkrdnz** [vuex-orm/plugin-search#6]
Hi, there is a typescript error with version 0.33.0 of vuex-orm/core like that

```
Property 'search' does not exist on type 'Query<BaseModel>'.
```

Can you fix this?

**Comment by kiaking** [comment]
Oh, thanks for the report! I'll look into it!

**Comment by kiaking** [comment]
I think this issue has been solved by Vuex ORM Search 0.24.1. Could you try it out?
https://github.com/vuex-orm/plugin-search/releases/tag/v0.24.1

**Comment by spaceemotion** [comment]
Just FYI: I am not getting any errors with the latest versions so far.

**Comment by cuebit** [comment]
Thanks for the confirmation @spaceemotion 👍
